### ISSUE TITLE
Ingress template in Helm chart doesn't work in OpenShift

### ISSUE THREAD

**Issue by hancockjt** [dbeaver/team-edition-deploy#2]
The ingress resource in the Helm chart has complex annotations that require an nginx ingress controller. OpenShift uses an haproxy ingress controller. In particular, the path entries and the rewrite-target annotations rely on capture groups, which is not supported.

```yaml
kind: Ingress
metadata:
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: "/$1$2"
    ...
spec:
  rules:
    - host: "xxx"
        - path: /(rm)(.*)
          pathType: Prefix
```

The regex in the path is meaningless in OpenShift / HAProxy, as is the capture group in the rewrite-target.
